modLoader="javafml"
loaderVersion="[${fml_min},)"
license="GPL v3.0"

[[mods]]
modId="potiondescriptions"
version="${mod_version}"
displayName="${mod_name}"
logoFile="examplemod.png"
authors="Azmalent"
description='''
Adds effect descriptions to potion tooltips.
'''

[[dependencies.potiondescriptions]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="botania"
    mandatory=false
    versionRange="[1.16.3-407,)"
    ordering="BEFORE"
    side="CLIENT"

[[dependencies.potiondescriptions]]
    modId="xreliquary"
    mandatory=false
    versionRange="[1.3.5,)"
    ordering="BEFORE"
    side="CLIENT"
